#include "mscript/core/Word.hpp"

namespace ms {

    std::string to_string(const Word w) {
        switch (w) {
            case Word::Unknown:
                return "Unknown";
            case Word::Identifier:
                return "Identifier";
            case Word::Character:
                return "Character";
            case Word::Integer:
                return "Integer";
            case Word::String:
                return "String";
            case Word::Real:
                return "Real";
            case Word::Function:
                return "Function";
            case Word::Return:
                return "Return";
            case Word::While:
                return "While";
            case Word::Match:
                return "Match";
            case Word::Break:
                return "Break";
            case Word::False:
                return "False";
            case Word::Null:
                return "Null";
            case Word::True:
                return "True";
            case Word::Else:
                return "Else";
            case Word::Let:
                return "Let";
            case Word::For:
                return "For";
            case Word::In:
                return "In";
            case Word::If:
                return "If";
            case Word::Do:
                return "Do";
            case Word::And:
                return "And";
            case Word::Or:
                return "Or";
            case Word::Plus:
                return "Plus";
            case Word::Minus:
                return "Minus";
            case Word::Multiply:
                return "Multiply";
            case Word::Divide:
                return "Divide";
            case Word::Modulus:
                return "Modulus";
            case Word::Not:
                return "Not";
            case Word::Invert:
                return "Invert";
            case Word::BOr:
                return "BOr";
            case Word::BAnd:
                return "BAnd";
            case Word::BXor:
                return "BXor";
            case Word::LeftShift:
                return "LeftShift";
            case Word::RightShift:
                return "RightShift";
            case Word::Equals:
                return "Equals";
            case Word::NotEquals:
                return "NotEquals";
            case Word::Less:
                return "Less";
            case Word::Greater:
                return "Greater";
            case Word::LessEqual:
                return "LessEqual";
            case Word::GreaterEqual:
                return "GreaterEqual";
            case Word::PlusAssign:
                return "PlusAssign";
            case Word::MinusAssign:
                return "MinusAssign";
            case Word::MultiplyAssign:
                return "MultiplyAssign";
            case Word::DivideAssign:
                return "DivideAssign";
            case Word::ModulusAssign:
                return "ModulusAssign";
            case Word::LeftShiftAssign:
                return "LeftShiftAssign";
            case Word::RightShiftAssign:
                return "RightShiftAssign";
            case Word::BOrAssign:
                return "BOrAssign";
            case Word::BAndAssign:
                return "BAndAssign";
            case Word::BXorAssign:
                return "BXorAssign";
            case Word::Assign:
                return "Assign";
            case Word::Range:
                return "Range";
            case Word::Arrow:
                return "Arrow";
            case Word::Colon:
                return "Colon";
            case Word::Comma:
                return "Comma";
            case Word::Dot:
                return "Dot";
            case Word::LeftBracket:
                return "LeftBracket";
            case Word::RightBracket:
                return "RightBracket";
            case Word::LeftBrace:
                return "LeftBrace";
            case Word::RightBrace:
                return "RightBrace";
            case Word::LeftParen:
                return "LeftParen";
            case Word::RightParen:
                return "RightParen";
            case Word::EndOfFile:
                return "EndOfFile";
            default:
                return "unknown";
        }
    }

}
